### ISSUE TITLE
MySQL language missing when MSSQL extension is enabled

### ISSUE THREAD

**Issue by coldacid** [jakebathman/mysql-syntax#15]
When the mssql extension is enabled in Visual Studio Code, the language service provided by this extension is completely unavailable due to conflicting language IDs (both register "sql" but the mssql extension gets there first). I suggest following the lead of the doublefint.pgsql extension and us the ID "mysql" instead to work around this problem.

Tested with:
* Visual Studio Code 1.23.1
* mssql extension (ms-mssql.mssql) 1.3.1
* MySQL Syntax (jakebathman.mysql-syntax) 1.3.1

**Comment by kAlvaro** [comment]
Probably the same as #9

**Comment by coldacid** [comment]
Yeah looks like.
