### ISSUE TITLE
IF NOT EXISTS shows incorrect syntax

### ISSUE THREAD

**Issue by mikey-js** [jakebathman/mysql-syntax#31]
The following line is showing to have syntax errors even though this is correct syntax for mysql:

CREATE DATABASE IF NOT EXISTS mydatabase;

**Comment by jakebathman** [comment]
What do you mean by syntax errors? This extension isn't a linter, and shouldn't cause any syntax error issues to be shown. You might be getting an error from another extension you have installed.

Unless you mean that it's not formatting that syntax correctly, which I can look into if so.

**Comment by mikey-js** [comment]
Oh you are right, It was using mssql error reporting. It works fine.

**Comment by jakebathman** [comment]
Good to hear you got it figured out! Thanks 😸
